// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EventPlannerSampleTest.Models
{
    [Index("service_id", Name = "_idx")]
    [Index("client_id", Name = "client_id")]
    [Index("event_id", Name = "event_id")]
    [Index("request_id", Name = "request_id_idx")]
    [Index("vendor_id", Name = "vendor_id")]
    public partial class bookings
    {
        [Key]
        public int booking_id { get; set; }
        public int client_id { get; set; }
        public int vendor_id { get; set; }
        public int event_id { get; set; }
        public int? amount { get; set; }
        public int? service_id { get; set; }
        public int? request_id { get; set; }

        [ForeignKey("event_id")]
        [InverseProperty("bookings")]
        public virtual Events _event { get; set; }
        [ForeignKey("client_id")]
        [InverseProperty("bookings")]
        public virtual clients client { get; set; }
        [ForeignKey("request_id")]
        [InverseProperty("bookings")]
        public virtual requestresponse request { get; set; }
        [ForeignKey("service_id")]
        [InverseProperty("bookings")]
        public virtual services service { get; set; }
        [ForeignKey("vendor_id")]
        [InverseProperty("bookings")]
        public virtual vendor vendor { get; set; }
    }
}