// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EventPlannerSampleTest.Models
{
    [Index("clients_id", Name = "client_id_idx")]
    [Index("service_id", Name = "service_id_idx")]
    [Index("vendor_id", Name = "vendor_id_idx")]
    public partial class requestresponse
    {
        public requestresponse()
        {
            bookings = new HashSet<bookings>();
        }

        [Key]
        public int request_id { get; set; }
        public int? clients_id { get; set; }
        public int? vendor_id { get; set; }
        public int? service_id { get; set; }
        public int? response { get; set; }

        [ForeignKey("clients_id")]
        [InverseProperty("requestresponse")]
        public virtual clients clients { get; set; }
        [ForeignKey("service_id")]
        [InverseProperty("requestresponse")]
        public virtual services service { get; set; }
        [ForeignKey("vendor_id")]
        [InverseProperty("requestresponse")]
        public virtual vendor vendor { get; set; }
        [InverseProperty("request")]
        public virtual ICollection<bookings> bookings { get; set; }
    }
}