// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EventPlannerSampleTest.Models
{
    public partial class services
    {
        public services()
        {
            bookings = new HashSet<bookings>();
            requestresponse = new HashSet<requestresponse>();
        }

        [Key]
        public int service_id { get; set; }
        public int vendor_id { get; set; }
        public int event_id { get; set; }
        public int? amount { get; set; }

        [InverseProperty("service")]
        public virtual ICollection<bookings> bookings { get; set; }
        [InverseProperty("service")]
        public virtual ICollection<requestresponse> requestresponse { get; set; }
    }
}