// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EventPlannerSampleTest.Models
{
    [Index("sr_no", Name = "sr_no_UNIQUE", IsUnique = true)]
    public partial class user
    {
        public user()
        {
            clients = new HashSet<clients>();
            vendor = new HashSet<vendor>();
        }

        public int sr_no { get; set; }
        [Key]
        [StringLength(45)]
        public string email_id { get; set; }
        [Required]
        [StringLength(45)]
        public string password { get; set; }

        [InverseProperty("email")]
        public virtual ICollection<clients> clients { get; set; }
        [InverseProperty("email")]
        public virtual ICollection<vendor> vendor { get; set; }
    }
}