// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EventPlannerSampleTest.Models
{
    [Index("email_id", Name = "email_id")]
    public partial class vendor
    {
        public vendor()
        {
            bookings = new HashSet<bookings>();
            requestresponse = new HashSet<requestresponse>();
        }

        [Key]
        public int vendor_id { get; set; }
        [Required]
        [StringLength(100)]
        public string vname { get; set; }
        public int? contact { get; set; }
        [Required]
        [StringLength(45)]
        public string email_id { get; set; }
        [StringLength(45)]
        public string city { get; set; }

        [ForeignKey("email_id")]
        [InverseProperty("vendor")]
        public virtual user email { get; set; }
        [InverseProperty("vendor")]
        public virtual ICollection<bookings> bookings { get; set; }
        [InverseProperty("vendor")]
        public virtual ICollection<requestresponse> requestresponse { get; set; }
    }
}